<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DiarioRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
*/
class DiarioRepository extends EntityRepository
{
    public function getMaxDate()
    {
        $qb = $this->createQueryBuilder('d')
          ->select('d')
          ->addOrderBy('d.fecha', 'DESC')
          ->setMaxResults(1);

        return $qb->getQuery()
          ->getResult();
    }

    public function getMinDate()
    {
        $qb = $this->createQueryBuilder('d')
          ->select('d')
          ->addOrderBy('d.fecha', 'ASC')
          ->setMaxResults(1);

        return $qb->getQuery()
          ->getResult();
    }

}
