# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users:
            entity:
              class: AppBundle:Usuarios
              property: name

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            form_login:
              login_path: login
              check_path: login
              username_parameter: _username
              password_parameter: _password
              csrf_token_generator: security.csrf.token_manager
            logout:
              path: /logout
              target: /
    access_control:
        - { path: ^/login, roles: ['IS_AUTHENTICATED_ANONYMOUSLY'] }
        - { path: ^/admin, roles: ['ROLE_ADMIN'] }
        - { path: ^/user, roles: ['ROLE_USER'] }
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    encoders:
      AppBundle\Entity\User:
        algorithm: sha512
        # algorithm: plaintext
